---
title: "2021-2024 Map"
output:
  pdf_document: 
   latex_engine: xelatex
  html_document:
    df_print: paged
---


```{r}
library(tidyverse)
library(readxl)
library(sf)
library(tigris)
library(tmap)

data <- read_excel("dataset.xlsx") 

sexual_violence_data <- data %>%
  mutate(year = format(Time, "%Y"))

il_county_shapes <- counties(state = "IL", cb = TRUE, class = "sf")

```

```{r}
# 2021
total_crime_2021 <- sexual_violence_data %>%
  filter(year == "2021") %>%
  group_by(County) %>%
  summarise(total = sum(sexual_crime, na.rm = TRUE), .groups = "drop")

map_total_2021 <- left_join(il_county_shapes, total_crime_2021, by = c("NAME" = "County"))

tm_shape(map_total_2021) +
  tm_polygons(
    fill = "total",           
    palette = "Reds",           
    style = "cont",
    title = "Total Cases (2021)"
  ) +
  tm_text("NAME", size = 0.4) +
  tm_layout(legend.outside = TRUE, title = "2021")


```

```{r}
# 2022
total_crime_2022 <- sexual_violence_data %>%
  filter(year == "2022") %>%
  group_by(County) %>%
  summarise(total = sum(sexual_crime, na.rm = TRUE), .groups = "drop")

map_total_2022 <- left_join(il_county_shapes, total_crime_2022, by = c("NAME" = "County"))

tm_shape(map_total_2022) +
  tm_polygons(
    fill = "total",
    palette = "Reds",
    style = "cont",
    title = "Total Cases (2022)"
  ) +
  tm_text("NAME", size = 0.4) +
  tm_layout(legend.outside = TRUE, title = "2022")




```

```{r}
# 2023
total_crime_2023 <- sexual_violence_data %>%
  filter(year == "2023") %>%
  group_by(County) %>%
  summarise(total = sum(sexual_crime, na.rm = TRUE), .groups = "drop")

map_total_2023 <- left_join(il_county_shapes, total_crime_2023, by = c("NAME" = "County"))

tm_shape(map_total_2023) +
  tm_polygons(
    fill = "total",
    palette = "Reds",
    style = "cont",
    title = "Total Cases (2023)"
  ) +
  tm_text("NAME", size = 0.4) +
  tm_layout(legend.outside = TRUE, title = "2023")


```

```{r}
# 2024
total_crime_2024 <- sexual_violence_data %>%
  filter(year == "2024") %>%
  group_by(County) %>%
  summarise(total = sum(sexual_crime, na.rm = TRUE), .groups = "drop")

map_total_2024 <- left_join(il_county_shapes, total_crime_2024, by = c("NAME" = "County"))

tm_shape(map_total_2024) +
  tm_polygons(
    fill = "total",
    palette = "Reds",
    style = "cont",
    title = "Total Cases (2024)"
  ) +
  tm_text("NAME", size = 0.4) +
  tm_layout(legend.outside = TRUE, title = "2024")



```

```{r}
# (per 10,000) 
plot_rate_map_facet <- function(data, year, map_sf) {
  county_year_summary <- data %>%
    filter(year == year) %>%
    group_by(County) %>%
    summarise(total_crimes = sum(sexual_crime, na.rm = TRUE),
              population = first(population),
              .groups = "drop") %>%
    mutate(rate_per_10000 = (total_crimes / population) * 10000)

  final_map <- left_join(map_sf, county_year_summary, by = c("NAME" = "County"))

  tm_shape(final_map) +
    tm_polygons(
      fill = "rate_per_10000",
      palette = "Blues",
      style = "cont",  
      title = paste("Per 10,000 (", year, ")", sep = "")
    ) +
    tm_text("NAME", size = 0.4) +
    tm_layout(legend.outside = TRUE, title = paste(year))
}


```

```{r}
# 2021(per 10,000) 
plot_rate_map_facet(sexual_violence_data, "2021", il_county_shapes)

```

```{r}
# 2022(per 10,000) 
plot_rate_map_facet(sexual_violence_data, "2022", il_county_shapes)

```

```{r}
# 2023(per 10,000) 
plot_rate_map_facet(sexual_violence_data, "2023", il_county_shapes)

```

```{r}
# 2024(per 10,000) 
plot_rate_map_facet(sexual_violence_data, "2024", il_county_shapes)
```





